dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.3.2
compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.3.2'
dotenv: .env
networks:
  default: development
  goerli: active
  sepolia: active
  bloxberg: active
wallets:
  from_key: ${PRIVATE_KEY}
